### ISSUE TITLE
How can I run the SDM in Docker in local mode?

### ISSUE THREAD

**Issue by jessitron** [atomist/docs#257]
(I don't have an answer to this question now. I could dig in and find out if people upvote this issue.)

Upvote this issue if you want this! (by clicking the little smiley face above this description and choosing thumbs up. Or leave a comment)

**Comment by cdupuis** [comment]
`docker run -e ATOMIST_MODE=local ....`

**Comment by jessitron** [comment]
yes but it doesn't receive local commit notices
