### ISSUE TITLE
Fix nav menus for responsive

### ISSUE THREAD

**Issue by jrday** [atomist/docs#265]
When you reduce horizontal window size, eventually the left-nav of docs get collapsed into a hamburger menu. A couple of issues with how it works right now:

1. The left nav gets collapsed while the right nav (in-page outline) remains expanded.
2. The collapsed hamburger menu is not very visible.

![Screen Shot 2018-11-26 at 9.08.42 PM.png](https://images.zenhubusercontent.com/57927694e40e5714b16c6a38/3ab3dc13-ea28-4016-a46e-e6338a6eb85e)

Once reduced further, the right menu goes away, and we get this:

![Screen Shot 2018-11-26 at 9.20.44 PM.png](https://images.zenhubusercontent.com/57927694e40e5714b16c6a38/b1178ce3-3784-4c66-acbe-7d5932f9975c)

Fixes:

* [ ] Remove the right-side menu entirely. It doesn't really serve an important purpose (it's an outline of the current page) and takes screen real estate to do so. Let's just nix it.
* [ ] Make the hamburger menu easier to find. Currently, it's just too subtle

![subtle.png](https://images.zenhubusercontent.com/57927694e40e5714b16c6a38/a2702055-9a30-4274-9e4b-992a017f3d3a)

**Comment by benjordan** [comment]
Requested changes completed and pushed.

**Comment by gjtorikian** [comment]
Confirmed fixed!
