### ISSUE TITLE
Run your command"

### ISSUE THREAD

**Issue by timothysparg** [atomist/docs#281]

**Comment by timothysparg** [comment]
Developer Guide → SDM Development → Commands → Run your command

It is unclear here that the cli command can only be run against the SDM in local mode.

Either it should be explicitly mentioned as such, or the configuration should be shown that allows the cli commands to be executed against a SDM running in team mode

**Comment by jessitron** [comment]
@timothysparg thank you for this comment! sorry it took me so long. Does the fix clarify it? ... is it in the right place?

**Comment by timothysparg** [comment]
@jessitron that will do the trick, thanks.
