### ISSUE TITLE
Update "dry run" to "branch aware"

### ISSUE THREAD

**Issue by jessitron** [atomist/docs#290]

**Comment by gjtorikian** [comment]
@jessitron, was this meant for [this page](https://github.com/atomist/docs/blob/c075c7c177e2b8d61a7f2786a820a41cbffe8163/docs/developer/transform.md#L18), or the `OnDryRunBuildComplete` function name [over here](https://github.com/atomist/docs/blob/16a5981ed52b274a5943a765fcd764a465a111b3/docs/developer/putting-it-together.md#L73)? (Or both?)
