### ISSUE TITLE
Default Kubernetes Resource Kinds link mangled under Fetching Resources section  

### ISSUE THREAD

**Issue by donovanmuller** [atomist/docs#333]
From https://github.com/atomist/docs/pull/332 the `... Resource Kinds` link is not rendering correctly.

![4FB144CF-700E-47F3-96A0-E3996821E927](https://user-images.githubusercontent.com/1175891/63224140-36df5b80-c1c0-11e9-9e53-548670e32785.png)

**Comment by ddgenome** [comment]
This was fixed here https://github.com/atomist/docs/commit/08290414ff4702f38a6634425d77ebf4b5805c8e it just has not been released yet. I'll update this issue when it is released.

**Comment by ddgenome** [comment]
This fix is out.
