### ISSUE TITLE
 Non-index and no follow  -- Exclude all documentation pages from search results

### ISSUE THREAD

**Issue by murban74** [atomist/docs#346]
I know two ways on how to create the exclude and I'm not sure which one is best for documentation as I don't know how it's set up.

1. Add a Robots.txt file
2. Add a "noindex" and "nofollow" metatag  to the <head> sections of pages -- <META NAME="robots" CONTENT="noindex,nofollow">

Let me know what else you need from me regarding this request.

**Comment by cdupuis** [comment]
This is now done and deployed. Please verify that it is what you wanted @murban74.
