### ISSUE TITLE
Move SDM docs links to footer

### ISSUE THREAD

**Issue by ddgenome** [atomist/docs#353]

**Comment by ddgenome** [comment]
@murban74 @jennstar121 the change can be reviewed on the docs staging site: https://docs.atomist.services/

**Comment by murban74** [comment]
I reviewed the page twice and missed where the SDM guide. I had to do `command f.`

Change SDM Guide to `Access the SDM Guide >>`
Adopt same styling as next/previous navigation titles (e.g. "Getting Started"), but sized 14px
Put in 2 line breaks

**Comment by cdupuis** [comment]
@murban74 checkout the page at https://docs.atomist.services/ now. I've moved the link to its own footer row and adopted the styling you suggested. 

Also removed the "powered by MkDocs" footer.

**Comment by murban74** [comment]
💥

**Comment by ddgenome** [comment]
Should it have the forward arrow?

**Comment by cdupuis** [comment]
I added it because Michelle had >> in her text suggestion which looked odd close to the forward arrow of the next link. But we can remove that of course.

**Comment by ddgenome** [comment]
To me, its current location, styling, and the arrow give the impression it is part of the docs navigation, not linking to a "separate set" of docs.

**Comment by murban74** [comment]
Let’s keep as is for now. The >> gets used in some of our material as an indication to click.

Closing this issue

**Comment by ddgenome** [comment]
It's not using &raquo;, it's using the same arrow as the Next link:

<img width="200" alt="sdm-guide-arrow" src="https://user-images.githubusercontent.com/57881/102236772-83709f00-3eb9-11eb-939e-d5e9c0190169.png">

**Comment by jennstar121** [comment]
I suggest we use the >> and move the link to the left, aligned w/ the copyright info below. I also suggest the link appears on the darker background (along w/ copyright and social buttons), as opposed to the lighter background which houses the docs navigation. @cdupuis is it possible to make those couple changes?

**Comment by murban74** [comment]
No more changes on this.

We are moving forward with what is in staging. We can revisit when it makes
sense to take a deep dive and improve the documentation site.  Closing.
