### ISSUE TITLE
Review https://docs.atomist.services/tutorials/prevent-new-vulnerabilities/

### ISSUE THREAD

**Issue by cdupuis** [atomist/docs#359]
* Throughout the tutorial inconsistent use of case in headers: eg. _2. Fork the test repository_  vs _7. Simulate a Deployment_
* line 16: image needs an update to reflect recent changes in check run formatting
* line 37: missing `.` at the end of sentence
* line 53: why is _activated on each repository_ linking to the _simulate-a-deployment_ section? I would have expected this to point at a docs page about how to enable a policy on a repo using dso
* line 105: I believe the _actions_ should be upper case when used with GitHub: _GitHub Actions workflow_
* line 106: missing `.` at the end of sentence
* line 139/140: _push your Dockerfile_ - this should probably read _push your Docker Image_
* line 143: image needs an update
* in the rendered page I see lots of empty whitespace just before _## 7. Simulate a Deployment_. not sure why though.
* line 248: image needs an update
* line 252: image needs an update

**Comment by slimslenderslacks** [comment]
- [ ] line 16: image needs an update to reflect recent changes in check run formatting**
- [ ] line 248: image needs an update
- [ ] line 252: image needs an update
