### ISSUE TITLE
Linking Images (GitHub Actions)

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/docs#375]
https://docs.atomist.com/integration/linking-images/#github-actions

@cdupuis - I didn't totally follow the explanation this morning but I think there are two things here.

1.  org.opencontainer metadata is now added automatically
2.  there's a way to configure the github actions so that PRs with multiple commits don't use merge commits

Can we improve our documentation here?

**Comment by cdupuis** [comment]
@slimslenderslacks I think there are a few things we could improve

* I _think_ the `org.opencontainer` labels are now added automatically as seen in this Action execution https://github.com/jeanlaurent/kamoulox/runs/6226599761?check_suite_focus=true for this workflow file https://github.com/jeanlaurent/kamoulox/blob/master/.github/workflows/docker-image.yml#L31. Based on this I think we can reduce the set of labels that have to be added to just our `com.atomist.containers.image.dockerfile`
* We should add a link and note to https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
